### ISSUE TITLE
False positives when clicking on URLs with cmd (ctrl)

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/PopupBlocker#116] opened 2018-05-24 11:17 UTC
**STR:**
1. open this [page](https://vc.ru/38674-tinkoff-bank-anonsiroval-zapusk-centra-razrabotki-v-sochi)
2. press cmd (ctrl) and click on any link on the page, line in this [video](https://uploads.adguard.com/up05_ydr9d.mp4):  

**Expected result**
There is no alert window on the page

**Actual result**
After you click on the link, the alert window appears

**Environment:** 
Popup Blocker by AdGuard 2.5.1 - **Chrome extension**
Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by seanl-adg** [comment] 2018-06-14 14:19
Duplicate of https://github.com/AdguardTeam/PopupBlocker/issues/87

**Closed** 2019-10-24 11:58 UTC
Labels: Browser extension, P2: High, bug
