### ISSUE TITLE
tinder.com - false positive

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/PopupBlocker#70] opened 2017-12-28 15:27 UTC
If you click on the Facbook button, the PopupBlocker blocks the log in (https://tinder.com/app/login).

![image](https://user-images.githubusercontent.com/10995998/34414802-a6a081da-ebeb-11e7-866d-6caa56521eb1.png)

![image](https://user-images.githubusercontent.com/10995998/34414819-b61b33c6-ebeb-11e7-8ade-25bceb1a770a.png)

[tinder.com-1514474719499.log](https://github.com/AdguardTeam/PopupBlocker/files/1591478/tinder.com-1514474719499.log)

**Comment by seanl-adg** [comment] 2018-01-18 07:15
This is caused by React. It seems that the react detection introduced in https://github.com/AdguardTeam/PopupBlocker/issues/55 is not enough in this case. 
One way to proceed is using the detection mechanism used by [react-devtools](https://github.com/facebook/react-devtools) browser extension detects react instances.

**Comment by ameshkov** [comment] 2018-01-18 07:56
@seanl-adg that'd work

**Comment by seanl-adg** [comment] 2018-03-13 05:34
Fixed by https://github.com/AdguardTeam/PopupBlocker/commit/25a6416315a6513c8b67a976ae9da512de1d8721

**Closed by seanl-adg** 2018-03-13 05:34 UTC
Labels: bug
