### ISSUE TITLE
ubisoft.com incorrect blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/PopupBlocker#55] opened 2017-11-07 05:54 UTC
Report from the Telegram channel:

> I need a bit help. On https://www.ubisoft.com/ apparently AdGuard inteferes with the site function. When I clicked my account management link, Adguard reacted and blocked the pop up. It also asked me on that page if I wanted to allow it. I pressed yes to allow it and clicked the same link again, but adguard again asked me if I want to put it in whitelist and blocks the popup. This happened for another round, so then instead of answering yes, I just disabled adguard from my systray altogether and relogin to the ubisoft account and it worked :<

**Comment by seanl-adg** [comment] 2017-11-10 11:12
It should be fixed by https://github.com/AdguardTeam/PopupBlocker/commit/e43b49605d39baaa2ccc1368a9b6cd03fccdf58c.This is caused by a react instance used in account management dropdown menu. It was previously undetected, and I added another selector check for react. Usage of such custom `data-*` attributes are being reduced in react (https://reactjs.org/blog/2016/04/07/react-v15.html#document.createelement-is-in-and-data-reactid-is-out) but they will still be present. If we encounter a case where this is not enough, we may need to go to a full-fledged approach as in [react-devtools](https://github.com/facebook/react-devtools).

**Closed** 2018-01-18 07:12 UTC
Labels: bug
